### PR TITLE
Improve list of files excluded from build

### PR DESCRIPTION
**Pull request by sgiehl**
While building the automated release action I had a look through the list of excluded files and improved / update it.
There should now be a couple more files excluded.

### CODE REVIEW

**Review by justinvelluppillai — APPROVED** [review]
Did not check them all but mostly looks like you're removing some that have been added, others that are removed twice in script (eg .travis.yml, bower.json). Looks ok to me overall.

**Comment by tsteur** [comment]
Do any of the files like `vendor/twig/twig/.php-cs-fixer.dist.php` need to be deleted manually in an update script?

**Comment by sgiehl** [comment]
@tsteur No. that should be handled by the fix I provided for the updater, which should also handle hidden files. But we maybe should avoid merging this one before Matomo 4.6.2 was released, as https://github.com/matomo-org/matomo/pull/18447 won't be included there.

**Comment by tsteur** [comment]
👍

**Comment by sgiehl** [comment]
Merging this one, as next release will be most likely a 4.7.0 beta

**Pull request merged**
