### PR TITLE
Remove unneeded files in node_modules when building >= Matomo 4

### PR DESCRIPTION
**Pull request by diosmosis**

### CODE REVIEW

**Comment by aureq** [comment]
Hi @diosmosis 

A few comments on this PR if that's ok.

1. Could it be possible to keep `archives/.gitkeep` as it's used when I publish the `.deb` package.
2. There's a long list of files you are removing which is great. Seeking your opinion here, do you thin it would be beneficial to externalise that file/dir list to a separate text file and have the script read from it instead?

Cheers

**Comment by diosmosis** [comment]
> Could it be possible to keep archives/.gitkeep as it's used when I publish the .deb package.

Was removed by mistake, I've added it back.

> There's a long list of files you are removing which is great. Seeking your opinion here, do you thin it would be beneficial to externalise that file/dir list to a separate text file and have the script read from it instead?

This is definitely a good idea, but I'm sure it's a lower priority compared to everything else in the 4.0 milestone. This sounds like something to put into a separate issue and triage.

**Comment by aureq** [comment]
Thank you @diosmosis for the feedback. This looks good to me but given the sensitivity of removing `.js` files, it would be great to have a 2nd reviewer. Maybe @mattab or @tsteur ?

I'm also curious to understand how the list of files to remove is generated. Maybe this is something that could be integrated into the building process my the `.deb` package.

**Comment by mattab** [comment]
@aureq the list is generated basically manually, files that are not needed are identified and added to the list manually. The only way to test is to cut a beta release and check it still all work as expected. I'll merge this one at some point and check that the beta (which will be deployed on the demo) still works.

**Pull request merged**
